#include<stdio.h>

int main()
{
    int n,a,b,c,d,e,f,g,h,i,s;
    scanf("%d",&n);
    a=n%10;
    b=(n/10)%10;
    c=(n/100)%10;
    d=(n/1000)%10;
    e=(n/10000)%10;
    f=(n/100000)%10;
    g=(n/1000000)%10;
    h=(n/10000000)%10;
    i=(n/100000000)%10;
    if(n==1000000000)
    {
    	printf("512");
	}
    else
    {
        if(i>=2)
        {
        	printf("511");
		}
        else
        {
            if(h>=2)
            {
                a=1;
                b=1;
                c=1;
                d=1;
                e=1;
                f=1;
                g=1;
                h=1;
            }
            else
            {
                if(g>=2)
                {
                    a=1;
                    b=1;
                    c=1;
                    d=1;
                    e=1;
                    f=1;
                    g=1;
                }
                else
                {
                    if(f>=2)
                    {
                        a=1;
                        b=1;
                        c=1;
                        d=1;
                        e=1;
                        f=1;
                    }
                    else
                    {
                        if(e>=2)
                        {
                            a=1;
                            b=1;
                            c=1;
                            d=1;
                            e=1;
                        }
                        else
                        {
                            if(d>=2)
                            {
                                a=1;
                                b=1;
                                c=1;
                                d=1;
                            }
                            else
                            {
                                if(c>=2)
                                {
                                    a=1;
                                    b=1;
                                    c=1;
                                }
                                else
                                {
                                    if(b>=2)
                                    {
                                        a=1;
                                        b=1;
                                    }
                                    else
                                    {
                                        if(a>=2)
                                        {
                                        	a=1;
										}
                                    }
                                }
                            }
                        }
                    }
                }
            }
            s=a+2*b+4*c+8*d+16*e+32*f+64*g+128*h+256*i;
            printf("%d",s);
        }
    }
}
